using UnityEngine;

namespace Potshot
{
    /// <summary>Bot difficulty knobs. Asset generated by PrefabFactory.</summary>
    public class BotSpec : ScriptableObject
    {
        public float reactionInterval = 0.2f;
        public float aimJitterDeg = 4f;
        public float preferredRangeMin = 8f;
        public float preferredRangeMax = 12f;
        public float fireRange = 16f;
        public float pickupDetourRange = 12f;
        public float wallProbeDistance = 3f;
    }
}
