using UnityEngine;

namespace Potshot
{
    /// <summary>
    /// Tank tuning values. Asset generated by PrefabFactory (get-or-create,
    /// GUID-stable) at Resources/Specs/TankSpec.asset. Feel targets from
    /// docs/gameplay.md; linear accel model so tests hit targets exactly:
    /// 0→6 u/s at 15 u/s² = 0.4 s.
    /// </summary>
    public class TankSpec : ScriptableObject
    {
        public float topSpeed = 6f;          // u/s
        public float accel = 15f;            // u/s² (also used for decel)
        public float hullTurnDegPerSec = 540f;
        public float turretDegPerSec = 360f;
    }
}
