using UnityEngine;

namespace Potshot
{
    /// <summary>
    /// Tank tuning values. Asset generated by PrefabFactory (get-or-create,
    /// GUID-stable) at Resources/Specs/TankSpec.asset. Feel targets from
    /// docs/gameplay.md; linear accel model so tests hit targets exactly:
    /// 0→6 u/s at 15 u/s² = 0.4 s.
    /// </summary>
    public class TankSpec : ScriptableObject
    {
        public float topSpeed = 7f;          // u/s (bumped from 6, playtest 2026-08-04)
        public float accel = 17.5f;          // u/s² — keeps the 0.4 s reach
        public float hullTurnDegPerSec = 540f;
        public float turretDegPerSec = 360f;
        public float boostMultiplier = 1.8f; // speed AND accel while boosting
        public float boostDuration = 1f;     // s
        public float boostCooldown = 4f;     // s, starts when boost fires
    }
}
