using UnityEngine;

namespace Potshot
{
    /// <summary>
    /// Weapon tuning. Assets generated by WeaponFactory from its C# data
    /// table (single source of truth, diff-reviewable) into
    /// Resources/Specs/Weapons/.
    /// </summary>
    public class WeaponSpec : ScriptableObject
    {
        public string id;
        public string displayName;
        public float fireCooldown = 0.8f;
        public float projectileSpeed = 14f; // ignored by mortar (ballistic solve)
        public float damage = 50f;
        public int ricochets;
        public int pelletCount = 1;
        public float spreadAngleDeg;        // fan when pelletCount>1, jitter when 1
        public bool useGravity;             // mortar lob
        public float aoeRadius;             // >0: AoE on impact, no direct damage
        public float projectileScale = 0.3f;
        public Material projectileMaterial; // saved asset (no instanced leaks)
    }
}
